# Macro file for example B1
# 
# To be run preferably in batch, without graphics:
# % exampleB1 run2.mac
#
/control/verbose 0
/run/verbose 0
/tracking/verbose 0
#
# 14 MeV neutron to the direction (0.,0.,1.)
# 
#
# /gun/particle neutron
# /gun/energy 14 MeV
#
# /run/printProgress 1000000
# /run/beamOn 10000000
# 
# 1 MeV neutron to the direction (0.,0.,1.)
# 
#
/gun/particle neutron
/gun/energy 1 MeV
#
/run/printProgress 1000000
/run/beamOn 10000000
