# Macro file for example B1
# 
# To be run preferably in batch, without graphics:
# % exampleB1 run2.mac
#
/control/verbose 0
/run/verbose 0
/tracking/verbose 0
#
# 14 MeV neutron to the direction (0.,0.,1.)
# 1000 events
#
/gun/particle neutron
/gun/energy 14 MeV
#
/run/printProgress 1000
/run/beamOn 10000
# 
# proton 210 MeV to the direction (0.,0.,1.)
# 1000 events
#
# /gun/particle proton
# /gun/energy 210 MeV
#
#/run/beamOn 1000
